# Generated by Django 4.1.1 on 2022-09-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jobContract',
            field=models.CharField(choices=[(' ', '------'), ('All', 'All'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='jobType',
            field=models.CharField(choices=[(' ', '------'), ('Digital & Design', 'Digital & Design'), ('Information Security / Cyber Security', 'Information Security / Cyber Security'), ('Project & Programme Management', 'Project & Programme Management'), ('Software Development & Engineering', 'Software Development & Engineering'), ('Technology Leadership', 'Technology Leadership'), ('Data & Analytics', 'Data & Analytics')], max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup_choices',
            field=models.CharField(choices=[(' ', '------'), ('talent', 'Talent'), ('recruiter', 'Recruiter')], max_length=512),
        ),
    ]
